#!/usr/bin/env bash
# === AliExpress Coin Bot — one-command setup (Linux/macOS) ===
# Usage: ./setup.sh [--no-start]
#   Installs deps + Chromium, creates .env on first run, then starts the bot.
set -euo pipefail
cd "$(dirname "$0")"

echo "=== AliExpress Coin Bot setup ==="

command -v node >/dev/null || { echo "[ERROR] Node.js 20+ not found. Install it, then re-run ./setup.sh"; exit 1; }

echo "[1/4] Installing dependencies..."
npm install --no-audit --no-fund

echo "[2/4] Installing headless Chromium for Playwright..."
npx playwright install chromium

if [ ! -f .env ]; then
  echo "[3/4] First run — creating .env ..."
  echo "Get BOT_TOKEN from @BotFather and your numeric chat ID from @userinfobot."
  read -r -p "BOT_TOKEN: " BOT_TOKEN
  read -r -p "ADMIN_CHAT_ID (your numeric chat ID): " ADMIN_CHAT_ID
  read -r -p "TZ [Africa/Algiers]: " TZ
  TZ=${TZ:-Africa/Algiers}
  ENCRYPT_SECRET=$(node -e "console.log(require('crypto').randomBytes(24).toString('hex'))")
  cat > .env <<EOF
# Generated by setup.sh — DO NOT COMMIT THIS FILE
BOT_TOKEN=${BOT_TOKEN}
ADMIN_CHAT_ID=${ADMIN_CHAT_ID}
ENCRYPT_SECRET=${ENCRYPT_SECRET}
MULTI_USER=false
TZ=${TZ}
EOF
  echo ".env created."
else
  echo "[3/4] .env already exists — keeping it."
fi

if [ "${1:-}" = "--no-start" ]; then
  echo "[4/4] Skipped start (--no-start)."
  exit 0
fi

echo "[4/4] Starting the bot... (Ctrl+C to stop)"
echo "Then open Telegram, send /start to your bot, and /addaccount to link AliExpress."
npm start
