@echo off
rem === AliExpress Coin Bot - one-command setup (Windows CMD) ===
rem Usage: setup.bat [--no-start]
rem Installs deps + Chromium, creates .env on first run, then starts the bot.
rem NOTE: intentionally flat (goto-based, no parenthesized if-blocks) because
rem cmd's block parser chokes on parentheses inside prompts/commands.
cd /d "%~dp0"

echo === AliExpress Coin Bot setup ===

where node >nul 2>nul
if not errorlevel 1 goto have_node
echo [ERROR] Node.js 20+ not found. Install it from https://nodejs.org then re-run setup.bat
exit /b 1
:have_node

echo [1/4] Installing dependencies...
call npm install --no-audit --no-fund
if not errorlevel 1 goto deps_ok
echo [ERROR] npm install failed.
exit /b 1
:deps_ok

echo [2/4] Installing headless Chromium for Playwright...
node node_modules\playwright\cli.js install chromium
if not errorlevel 1 goto chromium_ok
echo [ERROR] Chromium install failed. Check your connection and re-run setup.bat
exit /b 1
:chromium_ok

if exist .env goto have_env
echo [3/4] First run - creating .env ...
echo Get BOT_TOKEN from @BotFather and your numeric chat ID from @userinfobot.
echo.
set /p BOT_TOKEN=BOT_TOKEN:
set /p ADMIN_CHAT_ID=ADMIN_CHAT_ID:
set /p TZ=TZ [Africa/Algiers]:
if not "%TZ%"=="" goto tz_ok
set TZ=Africa/Algiers
:tz_ok
for /f %%i in ('powershell -NoProfile -Command "[guid]::NewGuid().ToString('N')"') do set ENCRYPT_SECRET=%%i
(
echo # Generated by setup.bat - DO NOT COMMIT THIS FILE
echo BOT_TOKEN=%BOT_TOKEN%
echo ADMIN_CHAT_ID=%ADMIN_CHAT_ID%
echo ENCRYPT_SECRET=%ENCRYPT_SECRET%
echo MULTI_USER=false
echo TZ=%TZ%
) > .env
echo .env created.
goto env_done
:have_env
echo [3/4] .env already exists - keeping it.
:env_done

if not "%~1"=="--no-start" goto do_start
echo [4/4] Skipped start (--no-start).
exit /b 0
:do_start
echo [4/4] Starting the bot... (Ctrl+C to stop)
echo Then open Telegram, send /start to your bot, and /addaccount to link AliExpress.
call npm start
